package rtp.demo.creditor.validation.rules;

import rtp.demo.creditor.validation.PaymentValidationRequest;
import rtp.demo.creditor.domain.account.Account;
import rtp.demo.creditor.domain.rtp.simplified.CreditTransferMessage;
import rtp.demo.creditor.validation.wrappers.CreditorBank;
import rtp.demo.creditor.validation.wrappers.ProcessingDateTime;
import java.util.HashSet;

dialect "java"

rule "Test"
no-loop
  when

  then
    System.out.println("Hello !");
end


query getValidationResults
    $validationResults := HashSet() from collect ( PaymentValidationRequest() )
end


